<template>
  <main class="explorer-page">
    <section class="hero">
      <v-container class="page-container">
        <div class="hero-content">
          <div>
            <div class="eyebrow">
              <span class="live-dot"></span>
              Open visual playground
            </div>
            <h1>Explore a new visual language.</h1>
            <p>
              Describe an image, generate a portrait artwork, and browse the latest experiments from everyone using the lab.
            </p>
          </div>

          <div class="hero-stats">
            <div>
              <strong>{{ jobs.length }}</strong>
              <span>Recent explorations</span>
            </div>
            <div>
              <strong>{{ completedJobs.length }}</strong>
              <span>Ready images</span>
            </div>
            <div>
              <strong>{{ activeJobCount }}</strong>
              <span>Generating</span>
            </div>
          </div>
        </div>
      </v-container>
    </section>

    <v-container class="page-container content-container">
      <v-card class="generator-card" rounded="xl" elevation="0">
        <header class="generator-header">
          <div>
            <div class="section-kicker">New image exploration</div>
            <h2>What should the image feel like?</h2>
            <p>Every prompt and generated image is public in this experimental gallery.</p>
          </div>
          <v-chip size="small" variant="tonal" prepend-icon="mdi-crop-portrait">
            1K · 9:16 PNG
          </v-chip>
        </header>

        <form @submit.prevent="handleSubmit">
          <div class="generator-grid">
            <div class="prompt-column">
              <StylePromptInput
                v-model="prompt"
                :error-message="promptError"
                :disabled="submitting"
                @blur="promptTouched = true"
              />

              <div class="prompt-ideas">
                <span>Try a direction</span>
                <div>
                  <v-chip
                    v-for="idea in promptIdeas"
                    :key="idea.label"
                    size="small"
                    variant="tonal"
                    @click="usePromptIdea(idea.prompt)"
                  >
                    {{ idea.label }}
                  </v-chip>
                </div>
              </div>
            </div>

            <aside class="track-context">
              <div>
                <v-icon icon="mdi-music-box-multiple-outline" size="24" />
                <div>
                  <strong>Add track context</strong>
                  <span>Optional</span>
                </div>
              </div>
              <p>
                Add a public BandLab track, then use
                <code>{trackName}</code> and <code>{trackGenre}</code> inside your prompt.
              </p>
              <v-text-field
                v-model="trackUrl"
                label="BandLab track URL"
                placeholder="https://test.bandlab.com/track/..."
                variant="outlined"
                density="comfortable"
                prepend-inner-icon="mdi-link-variant"
                :error-messages="trackUrlError"
                :disabled="submitting"
                clearable
                autocomplete="url"
                @blur="trackUrlTouched = true"
              />
            </aside>
          </div>

          <footer class="generator-footer">
            <div>
              <v-icon icon="mdi-eye-outline" size="17" />
              <span>Do not include private, personal, or secret information.</span>
            </div>
            <v-btn
              type="submit"
              color="primary"
              size="large"
              rounded="lg"
              prepend-icon="mdi-image-sparkles-outline"
              :loading="submitting"
            >
              Generate image
            </v-btn>
          </footer>
        </form>
      </v-card>

      <v-alert
        v-if="error"
        type="error"
        variant="tonal"
        closable
        class="mt-5"
        @click:close="clearError"
      >
        {{ error }}
      </v-alert>

      <section class="gallery-section">
        <header class="gallery-header">
          <div>
            <div class="section-kicker">Shared experiments</div>
            <h2>Visual exploration gallery</h2>
            <p>Browse the latest 50 prompts and images generated by everyone.</p>
          </div>
          <div class="gallery-actions">
            <span v-if="lastUpdatedAt">
              Updated {{ formatRelativeDate(lastUpdatedAt.toISOString()) }}
            </span>
            <v-btn
              icon="mdi-refresh"
              variant="tonal"
              size="small"
              aria-label="Refresh generated images"
              :loading="refreshing"
              @click="refreshJobs"
            />
          </div>
        </header>

        <div class="filters">
          <v-text-field
            v-model="search"
            label="Search prompts, tracks, or job IDs"
            prepend-inner-icon="mdi-magnify"
            variant="outlined"
            density="compact"
            hide-details
            clearable
          />
          <v-select
            v-model="statusFilter"
            :items="statusOptions"
            label="Status"
            variant="outlined"
            density="compact"
            hide-details
          />
        </div>

        <div class="result-line">
          {{ filteredJobs.length }} {{ filteredJobs.length === 1 ? 'image' : 'images' }}
          <span v-if="hasFilters">· {{ jobs.length }} total</span>
        </div>

        <div v-if="jobsLoading" class="image-grid">
          <v-skeleton-loader
            v-for="index in 8"
            :key="index"
            type="image, article"
            class="image-skeleton"
          />
        </div>

        <div v-else-if="filteredJobs.length" class="image-grid">
          <AiGeneratedImageCard
            v-for="job in filteredJobs"
            :key="job.jobId"
            :job="job"
            :deleting="deletingJobIds.has(job.jobId)"
            @delete="requestDelete"
          />
        </div>

        <div v-else class="empty-state">
          <div class="empty-state__icon">
            <v-icon
              :icon="jobs.length ? 'mdi-image-search-outline' : 'mdi-palette-swatch-outline'"
              size="42"
            />
          </div>
          <h3>{{ jobs.length ? 'No matching explorations' : 'Start the visual gallery' }}</h3>
          <p>
            {{ jobs.length
              ? 'Try clearing the search or status filter.'
              : 'Describe an art direction above and generate the first image.' }}
          </p>
          <v-btn v-if="hasFilters" variant="tonal" size="small" @click="clearFilters">
            Clear filters
          </v-btn>
        </div>
      </section>
    </v-container>

    <v-dialog v-model="deleteDialogOpen" max-width="460" :persistent="deletingCandidate">
      <v-card class="delete-dialog" rounded="xl">
        <div class="delete-dialog__icon">
          <v-icon icon="mdi-delete-outline" size="28" />
        </div>
        <h2>Delete this exploration?</h2>
        <p>
          It will be removed from the shared visual gallery. This action cannot be undone.
        </p>
        <blockquote v-if="deleteCandidate">
          {{ deleteCandidate.resolvedPrompt || deleteCandidate.promptTemplate }}
        </blockquote>
        <v-alert
          v-if="error"
          type="error"
          variant="tonal"
          density="compact"
          class="mt-4 text-left"
        >
          {{ error }}
        </v-alert>
        <div class="delete-dialog__actions">
          <v-btn
            variant="text"
            :disabled="deletingCandidate"
            @click="closeDeleteDialog"
          >
            Cancel
          </v-btn>
          <v-btn
            color="error"
            prepend-icon="mdi-delete-outline"
            :loading="deletingCandidate"
            @click="confirmDelete"
          >
            Delete image
          </v-btn>
        </div>
      </v-card>
    </v-dialog>

    <v-snackbar v-model="showSuccess" color="success" :timeout="4500">
      <v-icon icon="mdi-check-circle" class="mr-2" />
      Image job created. The gallery will update while it generates.
    </v-snackbar>
    <v-snackbar v-model="showDeleteSuccess" color="success" :timeout="3500">
      <v-icon icon="mdi-check-circle" class="mr-2" />
      Image exploration deleted.
    </v-snackbar>
  </main>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import AiGeneratedImageCard from '@/components/AiGeneratedImageCard.vue'
import StylePromptInput from '@/components/StylePromptInput.vue'
import { useAiGeneratedImages } from '@/composables/useAiGeneratedImages'
import type { AiGeneratedImageJob } from '@/types/aiImageGeneration'
import type { TrackVideoJobStatus } from '@/types/trackVideo'
import { formatRelativeDate } from '@/utils/formatters'

const {
  jobs,
  activeJobCount,
  jobsLoading,
  refreshing,
  submitting,
  deletingJobIds,
  error,
  lastUpdatedAt,
  loadJobs,
  refreshJobs,
  submitJob,
  deleteJob,
  clearError,
  stopPolling,
} = useAiGeneratedImages()

const prompt = ref('')
const trackUrl = ref<string | null>('')
const promptTouched = ref(false)
const trackUrlTouched = ref(false)
const showSuccess = ref(false)
const showDeleteSuccess = ref(false)
const deleteDialogOpen = ref(false)
const deleteCandidate = ref<AiGeneratedImageJob | null>(null)
const search = ref('')
const statusFilter = ref<'all' | TrackVideoJobStatus>('all')

const promptIdeas = [
  {
    label: 'Dreamlike editorial',
    prompt: 'Dreamlike editorial portrait, translucent fabrics, soft fog, pearl and cobalt palette, cinematic studio light',
  },
  {
    label: 'Organic sculpture',
    prompt: 'An impossible organic sculpture grown from glass, moss, and polished chrome, photographed at blue hour',
  },
  {
    label: 'Track cover',
    prompt: 'Create bold cover artwork for {trackName}, translating the energy of {trackGenre} into an unusual tactile world',
  },
]

const statusOptions = [
  { title: 'All statuses', value: 'all' },
  { title: 'Queued', value: 'queued' },
  { title: 'Generating', value: 'processing' },
  { title: 'Ready', value: 'completed' },
  { title: 'Failed', value: 'failed' },
]

function validateTrackUrl(value: string): string | null {
  if (!value) {
    return null
  }

  try {
    const url = new URL(value)
    const allowedHosts = ['bandlab.com', 'www.bandlab.com', 'test.bandlab.com']
    const uuid = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    const trackPath = new RegExp(`^/track/${uuid}/?$`, 'i')
    const queryEntries = [...url.searchParams.entries()]
    const hasValidQuery = queryEntries.length === 0
      || (
        queryEntries.length === 1
        && queryEntries[0][0] === 'revId'
        && new RegExp(`^${uuid}$`, 'i').test(queryEntries[0][1])
      )

    if (
      url.protocol !== 'https:'
      || !allowedHosts.includes(url.hostname)
      || !trackPath.test(url.pathname)
      || !hasValidQuery
      || url.hash
    ) {
      return 'Use a valid public BandLab track URL.'
    }

    return null
  } catch {
    return 'Use a valid public BandLab track URL.'
  }
}

const rawPromptError = computed(() => {
  const value = prompt.value.trim()
  if (!value) {
    return 'A prompt is required.'
  }
  if (prompt.value.length > 2000) {
    return 'Keep the prompt within 2,000 characters.'
  }
  if (
    (value.includes('{trackName}') || value.includes('{trackGenre}'))
    && !trackUrl.value?.trim()
  ) {
    return 'Add a track URL when using track metadata placeholders.'
  }
  return null
})
const rawTrackUrlError = computed(() => validateTrackUrl(trackUrl.value?.trim() || ''))
const promptError = computed(() => promptTouched.value ? rawPromptError.value : null)
const trackUrlError = computed(() => trackUrlTouched.value ? rawTrackUrlError.value : null)
const deletingCandidate = computed(() => (
  deleteCandidate.value
    ? deletingJobIds.value.has(deleteCandidate.value.jobId)
    : false
))
const completedJobs = computed(() => jobs.value.filter(job => job.status === 'completed'))
const hasFilters = computed(() => (
  search.value.trim().length > 0 || statusFilter.value !== 'all'
))
const filteredJobs = computed(() => {
  const query = search.value.trim().toLowerCase()
  return jobs.value.filter(job => {
    if (statusFilter.value !== 'all' && job.status !== statusFilter.value) {
      return false
    }
    if (!query) {
      return true
    }

    return [
      job.promptTemplate,
      job.resolvedPrompt,
      job.track?.name,
      job.track?.genre,
      job.jobId,
    ].some(value => value?.toLowerCase().includes(query))
  })
})

function usePromptIdea(value: string): void {
  prompt.value = value
  promptTouched.value = false
}

async function handleSubmit(): Promise<void> {
  promptTouched.value = true
  trackUrlTouched.value = true
  if (rawPromptError.value || rawTrackUrlError.value) {
    return
  }

  clearError()
  const created = await submitJob(prompt.value, trackUrl.value?.trim() || undefined)
  if (created) {
    showSuccess.value = true
    prompt.value = ''
    trackUrl.value = ''
    promptTouched.value = false
    trackUrlTouched.value = false
  }
}

function clearFilters(): void {
  search.value = ''
  statusFilter.value = 'all'
}

function requestDelete(job: AiGeneratedImageJob): void {
  clearError()
  deleteCandidate.value = job
  deleteDialogOpen.value = true
}

function closeDeleteDialog(): void {
  if (deletingCandidate.value) {
    return
  }

  deleteDialogOpen.value = false
  deleteCandidate.value = null
}

async function confirmDelete(): Promise<void> {
  if (!deleteCandidate.value) {
    return
  }

  const deleted = await deleteJob(deleteCandidate.value.jobId)
  if (deleted) {
    deleteDialogOpen.value = false
    deleteCandidate.value = null
    showDeleteSuccess.value = true
  }
}

onMounted(() => {
  void loadJobs()
})

onBeforeUnmount(stopPolling)
</script>

<style scoped>
.explorer-page {
  min-height: calc(100vh - 68px);
}

.hero {
  position: relative;
  overflow: hidden;
  padding: 68px 0 82px;
  background:
    radial-gradient(circle at 10% 24%, rgba(116, 226, 255, 0.15), transparent 29%),
    radial-gradient(circle at 87% 15%, rgba(204, 128, 255, 0.2), transparent 30%),
    linear-gradient(145deg, #10131a, #08090c 68%);
}

.hero::after {
  position: absolute;
  right: -80px;
  bottom: -260px;
  width: 580px;
  height: 520px;
  content: '';
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 64% 36% 52% 48% / 39% 55% 45% 61%;
  box-shadow:
    0 0 0 42px rgba(116, 226, 255, 0.02),
    0 0 0 84px rgba(204, 128, 255, 0.018);
  transform: rotate(18deg);
}

.hero-content {
  position: relative;
  z-index: 1;
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 64px;
  align-items: end;
}

.eyebrow,
.section-kicker {
  color: #82e8ff;
  font-size: 0.7rem;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.13em;
}

.eyebrow {
  display: flex;
  gap: 8px;
  align-items: center;
  margin-bottom: 20px;
}

.live-dot {
  width: 7px;
  height: 7px;
  background: #82e8ff;
  border-radius: 50%;
  box-shadow: 0 0 0 5px rgba(130, 232, 255, 0.12);
}

.hero h1 {
  max-width: 780px;
  margin: 0;
  color: #f7f8f4;
  font-size: clamp(3rem, 7vw, 6.4rem);
  font-weight: 820;
  line-height: 0.92;
  letter-spacing: -0.068em;
}

.hero p {
  max-width: 680px;
  margin: 28px 0 0;
  color: rgba(247, 248, 244, 0.62);
  font-size: clamp(1rem, 1.6vw, 1.18rem);
  line-height: 1.65;
}

.hero-stats {
  display: grid;
  gap: 22px;
  min-width: 160px;
  padding-left: 28px;
  border-left: 1px solid rgba(255, 255, 255, 0.13);
}

.hero-stats div {
  display: flex;
  flex-direction: column;
}

.hero-stats strong {
  color: #f7f8f4;
  font-size: 1.8rem;
  line-height: 1;
}

.hero-stats span {
  margin-top: 5px;
  color: rgba(247, 248, 244, 0.45);
  font-size: 0.72rem;
}

.content-container {
  margin-top: -42px;
  padding-bottom: 80px;
}

.generator-card {
  position: relative;
  z-index: 2;
  padding: 28px;
  background:
    linear-gradient(135deg, rgba(130, 232, 255, 0.05), transparent 34%),
    rgb(var(--v-theme-surface));
  border: 1px solid rgba(var(--v-theme-on-surface), 0.1);
  box-shadow: 0 24px 70px rgba(0, 0, 0, 0.2) !important;
}

.generator-header,
.gallery-header {
  display: flex;
  gap: 20px;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 25px;
}

.generator-header h2,
.gallery-header h2 {
  margin: 0;
  font-size: clamp(1.6rem, 3vw, 2.25rem);
  line-height: 1.1;
  letter-spacing: -0.045em;
}

.generator-header p,
.gallery-header p {
  margin: 7px 0 0;
  color: rgba(var(--v-theme-on-surface), 0.48);
  font-size: 0.78rem;
}

.generator-grid {
  display: grid;
  grid-template-columns: minmax(0, 1.55fr) minmax(300px, 0.75fr);
  gap: 20px;
}

.prompt-column,
.track-context {
  min-width: 0;
}

.prompt-ideas {
  display: flex;
  gap: 12px;
  align-items: flex-start;
  margin-top: -4px;
}

.prompt-ideas > span {
  flex: 0 0 auto;
  padding-top: 4px;
  color: rgba(var(--v-theme-on-surface), 0.42);
  font-size: 0.67rem;
}

.prompt-ideas > div {
  display: flex;
  gap: 7px;
  flex-wrap: wrap;
}

.track-context {
  padding: 18px;
  background: rgba(var(--v-theme-on-surface), 0.035);
  border: 1px solid rgba(var(--v-theme-on-surface), 0.08);
  border-radius: 16px;
}

.track-context > div:first-child {
  display: flex;
  gap: 11px;
  align-items: center;
}

.track-context > div:first-child div {
  display: flex;
  flex-direction: column;
}

.track-context strong {
  font-size: 0.82rem;
}

.track-context span,
.track-context p {
  color: rgba(var(--v-theme-on-surface), 0.48);
  font-size: 0.68rem;
}

.track-context p {
  margin: 16px 0;
  line-height: 1.55;
}

.track-context code {
  color: rgb(var(--v-theme-primary));
}

.generator-footer {
  display: flex;
  gap: 24px;
  align-items: center;
  justify-content: space-between;
  margin-top: 22px;
  padding-top: 18px;
  border-top: 1px solid rgba(var(--v-theme-on-surface), 0.08);
}

.generator-footer > div {
  display: flex;
  gap: 8px;
  align-items: center;
  color: rgba(var(--v-theme-on-surface), 0.45);
  font-size: 0.7rem;
}

.gallery-section {
  margin-top: 62px;
}

.gallery-actions {
  display: flex;
  gap: 12px;
  align-items: center;
}

.gallery-actions span {
  color: rgba(var(--v-theme-on-surface), 0.48);
  font-size: 0.72rem;
}

.filters {
  display: grid;
  grid-template-columns: minmax(240px, 1fr) 190px;
  gap: 12px;
  padding: 14px;
  background: rgba(var(--v-theme-surface), 0.56);
  border: 1px solid rgba(var(--v-theme-on-surface), 0.08);
  border-radius: 16px;
}

.result-line {
  margin: 18px 2px 12px;
  color: rgba(var(--v-theme-on-surface), 0.5);
  font-size: 0.76rem;
}

.image-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 18px;
  align-items: start;
}

.image-skeleton {
  overflow: hidden;
  border-radius: 18px;
}

.delete-dialog {
  padding: 28px;
  text-align: center;
  background: rgb(var(--v-theme-surface));
}

.delete-dialog__icon {
  display: grid;
  place-items: center;
  width: 58px;
  height: 58px;
  margin: 0 auto;
  color: rgb(var(--v-theme-error));
  background: rgba(var(--v-theme-error), 0.11);
  border-radius: 18px;
}

.delete-dialog h2 {
  margin: 18px 0 0;
  font-size: 1.5rem;
  letter-spacing: -0.04em;
}

.delete-dialog > p {
  margin: 9px auto 0;
  color: rgba(var(--v-theme-on-surface), 0.54);
  font-size: 0.78rem;
  line-height: 1.55;
}

.delete-dialog blockquote {
  display: -webkit-box;
  margin: 18px 0 0;
  padding: 13px 15px;
  overflow: hidden;
  color: rgba(var(--v-theme-on-surface), 0.7);
  font-size: 0.73rem;
  font-style: normal;
  line-height: 1.5;
  text-align: left;
  background: rgba(var(--v-theme-on-surface), 0.04);
  border-radius: 12px;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
}

.delete-dialog__actions {
  display: flex;
  gap: 10px;
  justify-content: flex-end;
  margin-top: 24px;
}

.empty-state {
  display: flex;
  align-items: center;
  flex-direction: column;
  padding: 72px 24px;
  text-align: center;
}

.empty-state__icon {
  display: grid;
  place-items: center;
  width: 76px;
  height: 76px;
  color: rgb(var(--v-theme-primary));
  background: rgba(var(--v-theme-primary), 0.08);
  border: 1px solid rgba(var(--v-theme-primary), 0.18);
  border-radius: 24px;
}

.empty-state h3 {
  margin: 20px 0 0;
  font-size: 1.2rem;
}

.empty-state p {
  max-width: 420px;
  margin: 8px 0 18px;
  color: rgba(var(--v-theme-on-surface), 0.48);
  font-size: 0.78rem;
}

@media (max-width: 1000px) {
  .generator-grid {
    grid-template-columns: 1fr;
  }

  .image-grid {
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }
}

@media (max-width: 760px) {
  .hero-content {
    grid-template-columns: 1fr;
    gap: 40px;
  }

  .hero-stats {
    grid-template-columns: repeat(3, 1fr);
    padding: 20px 0 0;
    border-top: 1px solid rgba(255, 255, 255, 0.13);
    border-left: 0;
  }

  .image-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 620px) {
  .hero {
    padding-top: 48px;
  }

  .generator-card {
    padding: 20px 16px;
  }

  .generator-header,
  .gallery-header,
  .generator-footer {
    align-items: flex-start;
    flex-direction: column;
  }

  .generator-footer .v-btn {
    width: 100%;
  }

  .filters {
    grid-template-columns: 1fr;
  }

  .prompt-ideas {
    flex-direction: column;
  }

  .image-grid {
    gap: 12px;
  }
}
</style>
